title:              Qi's Space
email:              hqqh6006@gmail.com
description:        Welcome to my space!
author:             tthq
baseurl:            "/"
url:                "https://tthq6006.github.io"

# Social Profiles
twitter_username:   hqqh6006
github_username:    tthq6006
facebook_username:  hqqh6006
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
